name: 🚀 Pull Request
description: Submit changes to the project
title: "[PR] "
labels: ["pull request"]
assignees: ["HoleInOneGolfer"]
body:
  - type: input
    id: summary
    attributes:
      label: "📝 Summary"
      description: "Briefly summarize the changes made."
      placeholder: "Summary of the changes"

  - type: textarea
    id: changes
    attributes:
      label: "🔧 What's changed?"
      description: "List the major changes in this PR."
      placeholder: "- Added X\n- Updated Y\n- Removed Z"

  - type: textarea
    id: issue_link
    attributes:
      label: "🔗 Related Issue"
      description: "Link to the related issue (if any)."
      placeholder: "e.g., Closes #123"

  - type: input
    id: tests
    attributes:
      label: "✅ Tests"
      description: "Were tests added or updated?"
      placeholder: "Yes/No/Not applicable"

  - type: input
    id: additional_info
    attributes:
      label: "ℹ️ Additional Info"
      description: "Any other details?"
      placeholder: "Any other information"
