name: 🐛 Bug report
description: Report a bug in the project
title: "🐞 [BUG] "
labels: ["bug"]
assignees: ["HoleInOneGolfer"]
body:
  - type: textarea
    id: description
    attributes:
      label: "📋 Description"
      description: "What's the bug? Describe it briefly."
      placeholder: "Describe the bug"

  - type: input
    id: environment
    attributes:
      label: "🌍 Environment"
      description: "Where did this happen?"
      placeholder: "e.g., OS, Browser, Node.js version"

  - type: textarea
    id: steps
    attributes:
      label: "🔁 Steps to Reproduce"
      description: "How do we see this bug?"
      placeholder: "1. Do this\n2. Then this\n3. See error"

  - type: input
    id: additional_info
    attributes:
      label: "ℹ️ Additional Info"
      description: "Any other details?"
      placeholder: "Any other information"
