name: ✨ Feature request
description: Suggest a new feature or enhancement
title: "🚀 [FEATURE] "
labels: ["enhancement"]
assignees: ["HoleInOneGolfer"]
body:
  - type: textarea
    id: description
    attributes:
      label: "💡 Description"
      description: "What's your idea?"
      placeholder: "Describe the feature"

  - type: textarea
    id: reason
    attributes:
      label: "🤔 Why?"
      description: "Why would this be useful?"
      placeholder: "Explain why this feature is needed"

  - type: input
    id: additional_info
    attributes:
      label: "ℹ️ Additional Info"
      description: "Anything else we should know?"
      placeholder: "Any other information"
