name: 🔒 Security vulnerability
description: Report a security issue
title: "⚠️ [SECURITY] "
labels: ["security"]
assignees: ["HoleInOneGolfer"]
body:
  - type: textarea
    id: description
    attributes:
      label: "🔍 Description"
      description: "What's the security issue?"
      placeholder: "Briefly describe the vulnerability"

  - type: input
    id: environment
    attributes:
      label: "🌍 Environment"
      description: "Where was it found?"
      placeholder: "e.g., OS, Browser, Version"

  - type: textarea
    id: impact
    attributes:
      label: "⚠️ Impact"
      description: "What's the potential impact?"
      placeholder: "Describe the risk"

  - type: input
    id: confidentiality
    attributes:
      label: "🔐 Confidential?"
      description: "Should this stay private?"
      placeholder: "Yes/No"
