title: "" 
description: "" 
baseurl: ""  # No subdirectory; deploying to the root of docs.benbowles.me
url: "https://docs.benbowles.me"  # Custom domain URL

# Theme settings
theme: minima  # Using the Minima theme or another preferred theme

header_pages:
  - privacy.md
  - tos.md

# Plugins (optional)
plugins:
  - jekyll-feed  # Optional: Provides an RSS feed for your site

# Exclude these files and directories from the build process
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - .github/  # Exclude the root .github directory if it's present

# Defaults for pages (optional)
defaults:
  - scope:
      path: ""  # Applies to all files
    values:
      layout: "default"  # Use the default layout provided by the theme
