# _config.yml

title: ""  # Leave the title empty or set it to what you want
description: "An unofficial TOS and Privacy Policy for API requirements."

theme: minima  # Or any other theme you're using

# Disable showing the repo name as the title
defaults:
  - scope:
      path: ""  # Apply to all files
    values:
      title: ""  # This ensures no default title is used

# Optional configurations
permalink: pretty  # Use pretty URLs for other pages
