# _config.yml

title: ""  # Leave the title empty or set it to what you want
description: "An unofficial TOS and Privacy Policy for API requirements."

# Disable showing the repo name as the title
theme: minima  # Or any other theme you're using
defaults:
  - scope:
      path: ""  # Apply to all files
    values:
      title: ""  # This ensures no default title is used

# Other configurations can go here
markdown: kramdown
highlighter: rouge

# Base URL settings
baseurl: "" # Adjust if the site is in a subdirectory

# Optional configurations
permalink: pretty  # Optional, use pretty URLs
